# Generated by Django 4.0.4 on 2022-05-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='img1',
            field=models.ImageField(upload_to='img'),
        ),
        migrations.AlterField(
            model_name='events',
            name='name1',
            field=models.CharField(max_length=200),
        ),
    ]
